name: in_app_review_example
description: Demonstrates how to use the in_app_review plugin.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+4

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=3.17.0"

dependencies:
  flutter:
    sdk: flutter

  in_app_review:
    path: ../
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

